### ISSUE TITLE
Do 'chapter' clean up

### ISSUE THREAD

**Issue by jackiekazil** [pyladies/pyladies-kit#39]
I am currently working on a clean up of 'chapter' throughout this repo

**Comment by econchick** [comment]
YESSSSSSSSS :heart: :heart: :heart:

**Comment by jackiekazil** [comment]
@econchick would you mind if I deleted this -- https://github.com/pyladies/pyladies-kit/blob/master/docs/_index.orig.rst... it seems like it is in other places?

**Comment by econchick** [comment]
@jackiekazil yeah anything with a leading `_` is not compiled/included so it's safe to delete. Thanks!
