### ISSUE TITLE
kit.pyladies.com is wrongly configured.

### ISSUE THREAD

**Issue by tanvibhakta** [pyladies/pyladies-kit#46]
The Readme.md file asks us to look at the nicely formatted kit at kit.pyladies.org 

This domain is broken because it hasn't been properly formatted on CloudFare.

<img width="1280" alt="screen shot 2018-10-08 at 12 27 07 pm" src="https://user-images.githubusercontent.com/13763558/46595392-c5417600-caf5-11e8-854b-796b1dbe4ed0.png">

**Comment by mUtterberg** [comment]
![6691f158-c91d-435c-b60b-7f6cff26549d](https://user-images.githubusercontent.com/35174396/46601959-d15d1180-cabc-11e8-9f19-4df7ad74daed.png)
Can confirm. It worked before! But I got the same error as above when trying to access 
[https://kit.pyladies.com]/(https://kit.pyladies.com/) right now.

**Comment by mUtterberg** [comment]
![screen shot 2018-10-09 at 8 44 39 am](https://user-images.githubusercontent.com/35174396/46670242-a697b980-cb9f-11e8-94c7-eb9dbf2bd484.png)
It's back to working! https gives an SSL error, but http no longer gives the 1014.

**Comment by mUtterberg** [comment]
I think this config issue can now be closed, but there may still be a need for site admin to look into our SSL cert. [http://kit.pyladies.com](http://kit.pyladies.com) vs [https://kit.pyladies.com](https://kit.pyladies.com)

**Comment by econchick** [comment]
Thanks @tanvibhakta and @mUtterberg for filing the issue!

@mUtterberg yeah there's some issue with Cloudflare and Read the Docs with https & DNS. I do plan on migrating the kit to SSL as I did with www, it just seems to take a bit more work than I realized. Hopefully over the weekend I can sort it out!

Thanks again!
