### ISSUE TITLE
Broken link to Spreadshirt

### ISSUE THREAD

**Issue by amcasari** [pyladies/pyladies-kit#84]
There is a broken link to "Spreadshirt" on [Organizer/swag](https://github.com/pyladies/pyladies-kit/blob/master/docs/organizer/swag.rst)

Link points to: http://pyladies.spreadshirt.com/ which returns "No resource with given URL found"

**Comment by Mariatta** [comment]
Thanks for the report. @econchick shared with me the correct url, which is https://shop.spreadshirt.com/pyladies/

I've search through the repo and updated all the urls. The updated version should show up soon on readthedcos.
